{
#  "UserPortImap":     "1143",
#  "UserPortSmtp":     "1025",
#  "AllowProxy":       "false",
#  "CacheEnabled":     "true",
#  "CacheCompression": "true",
#  "CacheDir":         "./run/cache",
#  "X509Key":          "./run/key.pem",
#  "X509Cert":         "./run/cert.pem",
#  "CookieJar":        "./run/cookies.json",
#  "CredentialsStore": "./run/credentials.json",
#  "ServerAddress":    "[::0]"
}